# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MP4player
                                 A QGIS plugin
 play MP4 movie with gps log
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Yoichi Kayama/aeroasahi corporation
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core   import QgsMapLayerProxyModel,QgsProject

from qgis.PyQt.QtCore import QDir, Qt, QUrl
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from qgis.PyQt.QtWidgets import (QApplication, QFileDialog, QHBoxLayout, QLabel,
        QPushButton, QSizePolicy, QSlider, QStyle, QVBoxLayout, QWidget)
from qgis.PyQt.QtWidgets import QMainWindow,QWidget, QPushButton, QAction
from qgis.PyQt.QtGui import QIcon

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .MP4player_dialog import MP4playerDialog
import os.path

from  .videowindow import VideoWindow

class MP4player:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MP4player_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&MP4player')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MP4player', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/MP4player/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'動画再生'),
            callback=self.run,
            parent=self.iface.mainWindow())


        self.add_action(
            icon_path,
            text=self.tr(u'設定'),
            callback=self.runAdm,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        self.admfirst_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&MP4player'),
                action)
            self.iface.removeToolBarIcon(action)


    def select_layer( self, vlayer ):


        self.dlg.dateTimeComboBox.setLayer( vlayer )


    def play(self):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.mediaPlayer.pause()
        else:
            self.mediaPlayer.play()

    def mediaStateChanged(self, state):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.playButton.setIcon(
                    self.style().standardIcon(QStyle.SP_MediaPause))
        else:
            self.playButton.setIcon(
                    self.style().standardIcon(QStyle.SP_MediaPlay))

    def positionChanged(self, position):
        self.positionSlider.setValue(position)

    def durationChanged(self, duration):
        self.positionSlider.setRange(0, duration)

    def setPosition(self, position):
        self.mediaPlayer.setPosition(position)

    def handleError(self):
        self.playButton.setEnabled(False)
        self.errorLabel.setText("Error: " + self.mediaPlayer.errorString())


    def initVideo( self ):
        print( "select ")
        self.videoWidget = QVideoWidget()

        self.playButton = QPushButton()
        self.playButton.setEnabled(False)
        #self.playButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.playButton.clicked.connect(self.play)

        self.positionSlider = QSlider(Qt.Horizontal)
        self.positionSlider.setRange(0, 0)
        self.positionSlider.sliderMoved.connect(self.setPosition)

        self.errorLabel = QLabel()
        self.errorLabel.setSizePolicy(QSizePolicy.Preferred,
                QSizePolicy.Maximum)

        wid = QWidget(self.dlg.vwidget)
        #self.dlg.setCentralWidget(wid)

        # Create layouts to place inside widget
        controlLayout = QHBoxLayout()
        controlLayout.setContentsMargins(0, 0, 0, 0)
        controlLayout.addWidget(self.playButton)
        controlLayout.addWidget(self.positionSlider)

        layout = QVBoxLayout()
        layout.addWidget(self.dlg.vwidget)
        layout.addLayout(controlLayout)
        layout.addWidget(self.errorLabel)

        # Set widget to contain window contents
        wid.setLayout(layout)

        self.mediaPlayer.setVideoOutput(self.dlg.vwidget)
        self.mediaPlayer.stateChanged.connect(self.mediaStateChanged)
        self.mediaPlayer.positionChanged.connect(self.positionChanged)
        self.mediaPlayer.durationChanged.connect(self.durationChanged)
        self.mediaPlayer.error.connect(self.handleError)



    def runAdm(self):
        if self.admfirst_start== True:
            self.admfirst_start= False   

            self.loglayer = None  
            self.timefield = None
            self.mp4layer = None

            proj = QgsProject.instance()

            log_id = proj.readEntry("MP4Player",  
                                            "loglayer_id",
                                            None)

            #        proj.writeEntry("MP4Player", "loglayer_id", self.loglayer_id)
            #proj.writeEntry("MP4Player", "timefield", self.timefield)
            #proj.writeEntry("MP4Player", "mp4layer_id", self.mp4layer_id )


            if log_id is not None:
                print( log_id )
                self.loglayer_id= log_id[0]
                self.loglayer = proj.mapLayer(self.loglayer_id)

            mp4_id = proj.readEntry("MP4Player",  
                                            "mp4layer_id",
                                            None)

            if mp4_id is not None:
                print( mp4_id )
                self.mp4layer_id= mp4_id[0]
                self.mp4layer  = proj.mapLayer(self.mp4layer_id)       


            time_field_l  = proj.readEntry("MP4Player",  
                                            "timefield",
                                            None)

            if time_field_l is not None:
                self.timefield = time_field_l[0]


            self.dlg = MP4playerDialog()
            self.dlg.logLayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)

            self.dlg.logLayerComboBox.layerChanged.connect(self.select_layer)

            self.dlg.mp4LayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)   

        if self.loglayer is not None:
            self.dlg.logLayerComboBox.setLayer(self.loglayer)

            #self.configdlg.mMapLayerHenjyo.setLayer(self.marklayer )

        if self.timefield  is not None:
            self.timefield = self.dlg.dateTimeComboBox.setField( self.timefield  )
            #print(" log1")

        if self.mp4layer is not None:
            self.dlg.mp4LayerComboBox.setLayer(self.mp4layer) 
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.

            self.loglayer = self.dlg.logLayerComboBox.currentLayer()
            self.loglayer_id = self.loglayer.id()

            self.timefield = self.dlg.dateTimeComboBox.currentField()

            self.mp4layer = self.dlg.mp4LayerComboBox.currentLayer()

            self.mp4layer_id = self.mp4layer.id()
            proj = QgsProject.instance()

            proj.writeEntry("MP4Player", "loglayer_id", self.loglayer_id)
            proj.writeEntry("MP4Player", "timefield", self.timefield)
            proj.writeEntry("MP4Player", "mp4layer_id", self.mp4layer_id )

            #print( self.loglayer )

            #print( self.loglayer.id() )

            #pass



    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

            self.vdlg = VideoWindow()
            self.vdlg.setModel( self )

            self.vdlg.resize(640, 480)
            #self.initVideo()



        # show the dialog
        self.vdlg.show()
        # Run the dialog event loop
        #result = self.vdlg.exec_()
        # See if OK was pressed
        #if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
        #    pass
